# Generated by Django 4.2.11 on 2024-03-10 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UMTSBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("band", models.IntegerField()),
            ],
            options={
                "verbose_name": "UMTSBand",
                "db_table": "attgsaudit_umts_band",
                "unique_together": {("start", "end")},
            },
        ),
        migrations.CreateModel(
            name="NRBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(default="SFO", max_length=20)),
                ("arfcndl", models.IntegerField(default=0)),
                ("bschannelbwdl", models.IntegerField(default=0)),
                ("ssbfrequency", models.IntegerField(default=0)),
                ("ssboffset", models.IntegerField(default=0)),
                ("ssbduration", models.IntegerField(default=0)),
                ("ssbperiodicity", models.IntegerField(default=0)),
                ("ssbsubcarrierspacing", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "NRBand",
                "db_table": "attgsaudit_nr_band",
                "unique_together": {("market", "arfcndl", "bschannelbwdl")},
            },
        ),
        migrations.CreateModel(
            name="LTEearfcnBandBWLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earfcndl", models.IntegerField()),
                ("band", models.IntegerField()),
                ("bandwidth", models.IntegerField()),
            ],
            options={
                "verbose_name": "LTEearfcnBandBWLayer",
                "db_table": "attgsaudit_lte_earfcn_band_bw_layer",
                "unique_together": {("earfcndl",)},
            },
        ),
        migrations.CreateModel(
            name="LTECAPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pcell", models.CharField(max_length=100)),
                ("scell", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "LTECAPair",
                "db_table": "attgsaudit_lte_ca_pair",
                "unique_together": {("pcell", "scell")},
            },
        ),
        migrations.CreateModel(
            name="LTEBandBWLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band", models.IntegerField()),
                ("bandwidth", models.IntegerField()),
                ("layer", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "LTEBandBWLayer",
                "db_table": "attgsaudit_lte_band_bw_layer",
                "unique_together": {("band", "bandwidth")},
            },
        ),
        migrations.CreateModel(
            name="AuditJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "market",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "sites",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "dlonly",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("audit_type", models.CharField(default="LTE/NR", max_length=50)),
                (
                    "femto",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Running", max_length=20, null=True
                    ),
                ),
                (
                    "script",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("create_dt", models.DateTimeField(auto_now_add=True)),
                ("update_dt", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attgsaudit_audit_job",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AuditJob",
                "db_table": "attgsaudit_audit_job",
                "ordering": ("-update_dt",),
                "unique_together": {("version", "market", "sites", "create_dt")},
            },
        ),
    ]
