# Generated by Django 4.1.6 on 2024-02-23 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('remark', models.CharField(default='DB Update', max_length=100)),
                ('status', models.CharField(blank=True, default='Running', max_length=20, null=True)),
                ('script', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_dbupdate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_dbupdate',
                'ordering': ('-update_dt',),
                'unique_together': {('appname', 'user', 'create_dt')},
            },
        ),
    ]
