from tmobile.tmo_ix.tmo_xml_base import tmo_xml_base


class testScripts_DonotUse_lte(tmo_xml_base):
    def initialize_var(self):
        if self.node in self.usid.enodeb.keys():
            self.relative_path = [F'Sample_Scripts_DonotUse', F'{self.__class__.__name__}_{self.node}.mos']
            self.script_elements.extend(self.test_script())

    def test_script(self):
        lines = [
            'return', 'return', 'return', 'return',
            F'',
            F'#############:-NodeGroupSyncMember-:#############',
            F'Mixed Mode Radio LTE',
            F'lset SystemFunctions=1,Lm=1,FeatureState=CXC4011018$ featureState 1',
            F'',
            F'crn Transport=1,Synchronization=1,RadioEquipmentClock=1,NodeGroupSyncMember=1',
            F'administrativeState 1',
            F'selectionMode 1',
            F'syncNodePriority 1',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=A',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=B',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=C',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=D',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=E',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=F',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=G',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=H',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=J',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=K',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=L',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=M',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=N',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=P',
            F'syncRiPortCandidate Equipment=1,FieldReplaceableUnit={self.enbdata.get("bbuid", "")},RiPort=Q',
            F'end',
            F'',
            F'',
            F'',
            F'',
            F'',
            F'',
            F'#############:-Transport for MMBB with 2 VLANs-:#############',
            F'set ENodeBFunction=1$ upIpAddressRef null',
            F'set Transport=1,SctpEndpoint=LTE localIpAddress null',
            F'',

            F'crn Transport=1,VlanPort={self.enbdata.get("lte_vlan", "")}',
            F'vlanId {self.enbdata.get("lte_vlan", "")}',
            F'encapsulation Transport=1,EthernetPort={self.enbdata.get("TnPort", "")}',
            F'end',
            F'',
            F'crn Transport=1,Bridge=1',
            F'port Transport=1,VlanPort={self.enbdata.get("lte_vlan", "")}',
            F'end',
            F'',
            F'crn Transport=1,Router={self.enbdata.get("lte", "")}',
            F'hopLimit 64',
            F'pathMtuExpiresIPv6 86400',
            F'ttl 64',
            F'end',
            F'',
            F'crn Transport=1,Router={self.enbdata.get("lte", "")},InterfaceIPv4={self.enbdata.get("lte_interface", "")}',
            F'arpTimeout 300',
            F'bfdStaticRoutes 0',
            F'encapsulation Transport=1,Bridge=1',
            F'mtu 1500',
            F'pcpArp 6',
            F'end',
            F'',
            F'crn Transport=1,Router={self.enbdata.get("lte", "")},InterfaceIPv4={self.enbdata.get("lte_interface", "")},AddressIPv4=1',
            F'address {self.enbdata.get("lte_ip", "")}/{self.enbdata.get("lte_plength", "")}',
            F'configurationMode 0',
            F'dhcpClientIdentifierType 0',
            F'end',
            F'',
            F'crn Transport=1,Router={self.enbdata.get("lte", "")},RouteTableIPv4Static=1',
            F'end',
            F'',
            F'crn Transport=1,Router={self.enbdata.get("lte", "")},RouteTableIPv4Static=1,Dst=1',
            F'dst 0.0.0.0/0',
            F'end',
            F'',
            F'crn Transport=1,Router={self.enbdata.get("lte", "")},RouteTableIPv4Static=1,Dst=1,NextHop=1',
            F'address {self.enbdata.get("lte_gway", "")}',
            F'adminDistance 5',
            F'bfdMonitoring true',
            F'discard false',
            F'end',
            F'',
            F'',
            F'',
            F'set ENodeBFunction=1$ upIpAddressRef Transport=1,Router={self.enbdata.get("lte", "")},InterfaceIPv4={self.enbdata.get("lte_interface", "")},AddressIPv4=1',
            F'set Transport=1,SctpEndpoint=LTE localIpAddress Transport=1,Router={self.enbdata.get("lte", "")},InterfaceIPv4={self.enbdata.get("lte_interface", "")},AddressIPv4=1',
            F'',
            F'',
            F'',
            F'',
            F'',
            F'',
            F'//  crn Transport=1,SctpEndpoint=LTE',
            F'//  localIpAddress Transport=1,Router={self.enbdata.get("lte", "")},InterfaceIPv4={self.enbdata.get("lte_interface", "")},AddressIPv4=1',
            F'//  portNumber 36422',
            F'//  sctpProfile SctpProfile=LTE',
            F'//  end',
            F'',
            F'',
        ]
        return lines

    def create_data_path(self):
        if len(self.script_elements) == 0: return
        import os
        self.script_file = os.path.join(self.usid.base_dir, *self.relative_path)
        out_dir = os.path.dirname(self.script_file)
        if not os.path.exists(out_dir): os.makedirs(out_dir)
