# Generated by Django 4.1.6 on 2024-02-23 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('usm', models.CharField(max_length=50)),
                ('sw', models.CharField(max_length=50)),
                ('mmepool', models.CharField(max_length=50)),
                ('amfpool', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('gnbidlength', models.CharField(max_length=50)),
                ('plmn', models.CharField(max_length=550)),
            ],
            options={
                'verbose_name': 'Client',
                'db_table': 'vz_client',
                'unique_together': {('market', 'sw', 'usm')},
            },
        ),
        migrations.CreateModel(
            name='VZJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='Error', max_length=100)),
                ('status', models.CharField(default='Queued', max_length=100)),
                ('script', models.CharField(default='', max_length=100)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='vz.client')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'db_table': 'vz_job',
                'ordering': ('-update_dt',),
            },
        ),
        migrations.CreateModel(
            name='SW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ne_version', models.CharField(max_length=50)),
                ('release_version', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SW',
                'db_table': 'vz_sw',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Mme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmepool', models.CharField(max_length=50)),
                ('mmename', models.CharField(max_length=50)),
                ('mmeid', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MME',
                'db_table': 'vz_mme',
                'unique_together': {('mmepool', 'mmeid')},
            },
        ),
        migrations.CreateModel(
            name='Amf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amfpool', models.CharField(max_length=50)),
                ('amfname', models.CharField(max_length=50)),
                ('amfid', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'AMF',
                'db_table': 'vz_amf',
                'unique_together': {('amfpool', 'amfid')},
            },
        ),
    ]
