# Generated by Django 4.1.6 on 2024-02-23 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMFPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'AMFPool',
                'db_table': 'tmobile_amfpool',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('enm', models.CharField(max_length=50)),
                ('NTPServer1', models.CharField(max_length=50)),
                ('NTPServer2', models.CharField(max_length=50)),
                ('NTPServer3', models.CharField(max_length=50)),
                ('NTPServer4', models.CharField(max_length=50)),
                ('timeZone', models.CharField(max_length=50)),
                ('dnPrefix', models.CharField(max_length=100)),
                ('SubNetwork', models.CharField(max_length=100)),
                ('sUserName', models.CharField(max_length=50)),
                ('sUserpass', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('TnPort', models.CharField(blank=True, max_length=50)),
                ('gnbidlength', models.CharField(max_length=50)),
                ('PlmnList', models.CharField(max_length=550)),
                ('addPlmnList', models.CharField(max_length=550)),
                ('amfpool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.amfpool')),
            ],
            options={
                'verbose_name': 'Client',
                'db_table': 'tmobile_client',
            },
        ),
        migrations.CreateModel(
            name='MMEPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'MMEPool',
                'db_table': 'tmobile_mmepool',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swname', models.CharField(max_length=50)),
                ('nodeIdentBB', models.CharField(max_length=100)),
                ('nodeTypeBB', models.CharField(max_length=100)),
                ('UpPacBB', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Software',
                'db_table': 'tmobile_software',
                'unique_together': {('swname',)},
            },
        ),
        migrations.CreateModel(
            name='ScriptJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('status', models.CharField(blank=True, default='Queued', max_length=100, null=True)),
                ('script', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmobile_scriptjob', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TMOScriptJob',
                'db_table': 'tmobile_scriptjob',
                'ordering': ('-update_dt',),
            },
        ),
        migrations.CreateModel(
            name='MoName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moc', models.CharField(max_length=100)),
                ('moid', models.CharField(blank=True, max_length=100)),
                ('motype', models.CharField(max_length=20)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.software')),
            ],
            options={
                'verbose_name': 'MoName',
                'db_table': 'tmobile_moname',
                'unique_together': {('software', 'moc', 'moid', 'motype')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='mmepool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.mmepool'),
        ),
        migrations.AddField(
            model_name='client',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.software'),
        ),
        migrations.CreateModel(
            name='TermPointToMme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmeName', models.CharField(max_length=50)),
                ('termPointToMmeId', models.CharField(max_length=50)),
                ('ipAddress1', models.CharField(max_length=50)),
                ('ipAddress2', models.CharField(max_length=50)),
                ('ipv6Address1', models.CharField(max_length=50)),
                ('ipv6Address2', models.CharField(max_length=50)),
                ('mmeSupportLegacyLte', models.CharField(max_length=50)),
                ('mmeSupportNbIoT', models.CharField(max_length=50)),
                ('mmepool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.mmepool')),
            ],
            options={
                'verbose_name': 'TermPointToMMe',
                'db_table': 'tmobile_termpointmme',
                'unique_together': {('mmepool', 'mmeName')},
            },
        ),
        migrations.CreateModel(
            name='TermPointToAmf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amfName', models.CharField(max_length=50)),
                ('defaultAmf', models.CharField(max_length=50)),
                ('ipv4Address1', models.CharField(max_length=50)),
                ('ipv4Address2', models.CharField(max_length=50)),
                ('ipv6Address1', models.CharField(max_length=50)),
                ('ipv6Address2', models.CharField(max_length=50)),
                ('termPointToAmfId', models.CharField(max_length=50)),
                ('amfpool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.amfpool')),
            ],
            options={
                'verbose_name': 'TermPointToAmf',
                'db_table': 'tmobile_termpointamf',
                'unique_together': {('amfpool', 'termPointToAmfId')},
            },
        ),
        migrations.CreateModel(
            name='MoRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('child', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.software')),
            ],
            options={
                'verbose_name': 'MoRelation',
                'db_table': 'tmobile_morelation',
                'unique_together': {('parent', 'child', 'software', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='MoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.CharField(default='', max_length=11000)),
                ('flag', models.BooleanField(default=True)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.moname')),
            ],
            options={
                'verbose_name': 'MoDetail',
                'db_table': 'tmobile_modetail',
                'unique_together': {('mo', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='MoAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moc', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=100)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmobile.software')),
            ],
            options={
                'verbose_name': 'MoAttribute',
                'db_table': 'tmobile_moattribute',
                'unique_together': {('software', 'moc')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('cname', 'mname', 'software', 'enm')},
        ),
    ]
